version: "3.3"
services:
  postgres-service:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5000:5000"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: